apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit
  namespace: streamlit-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
      - name: streamlit
        image: mbrede/ccdemo:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8501
        env:
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: streamlit
  namespace: streamlit-demo
spec:
  type: NodePort
  selector:
    app: streamlit
  ports:
  - port: 8501
    targetPort: 8501
    nodePort: 30000