apiVersion: v1
kind: Service
metadata:
  name: streamlit
  namespace: streamlit-demo
spec:
  selector:
    app: streamlit
  ports:
  - port: 8501
    targetPort: 8501
    nodePort: 30000
  type: NodePort